// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_mcp/test/mcp_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_mcp/src/config/mcp_config.dart' as _i5;
import 'package:flutter_mcp/src/core/client_manager.dart' as _i7;
import 'package:flutter_mcp/src/core/llm_manager.dart' as _i14;
import 'package:flutter_mcp/src/core/server_manager.dart' as _i10;
import 'package:flutter_mcp/src/managers/client_info.dart' as _i9;
import 'package:flutter_mcp/src/managers/llm_info.dart' as _i15;
import 'package:flutter_mcp/src/managers/server_info.dart' as _i13;
import 'package:flutter_mcp/src/platform/platform_services.dart' as _i2;
import 'package:flutter_mcp/src/platform/tray/tray_manager.dart' as _i6;
import 'package:flutter_mcp/src/utils/resource_manager.dart' as _i16;
import 'package:mcp_client/mcp_client.dart' as _i8;
import 'package:mcp_llm/mcp_llm.dart' as _i12;
import 'package:mcp_server/mcp_server.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PlatformServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlatformServices extends _i1.Mock implements _i2.PlatformServices {
  MockPlatformServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isBackgroundServiceRunning =>
      (super.noSuchMethod(
            Invocation.getter(#isBackgroundServiceRunning),
            returnValue: false,
          )
          as bool);

  @override
  String get platformName =>
      (super.noSuchMethod(
            Invocation.getter(#platformName),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#platformName),
            ),
          )
          as String);

  @override
  _i4.Future<void> initialize(_i5.MCPConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [config]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> startBackgroundService() =>
      (super.noSuchMethod(
            Invocation.method(#startBackgroundService, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> stopBackgroundService() =>
      (super.noSuchMethod(
            Invocation.method(#stopBackgroundService, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> showNotification({
    required String? title,
    required String? body,
    String? icon,
    String? id = 'mcp_notification',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showNotification, [], {
              #title: title,
              #body: body,
              #icon: icon,
              #id: id,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> hideNotification(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hideNotification, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> secureStore(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#secureStore, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> secureRead(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#secureRead, [key]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> secureDelete(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#secureDelete, [key]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> secureContains(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#secureContains, [key]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> setTrayMenu(List<_i6.TrayMenuItem>? items) =>
      (super.noSuchMethod(
            Invocation.method(#setTrayMenu, [items]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setTrayIcon(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setTrayIcon, [path]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setTrayTooltip(String? tooltip) =>
      (super.noSuchMethod(
            Invocation.method(#setTrayTooltip, [tooltip]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void setLifecycleChangeListener(dynamic Function(dynamic)? listener) =>
      super.noSuchMethod(
        Invocation.method(#setLifecycleChangeListener, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> shutdown() =>
      (super.noSuchMethod(
            Invocation.method(#shutdown, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [MCPClientManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockMCPClientManager extends _i1.Mock implements _i7.MCPClientManager {
  MockMCPClientManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  String generateId() =>
      (super.noSuchMethod(
            Invocation.method(#generateId, []),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#generateId, []),
            ),
          )
          as String);

  @override
  void registerClient(
    String? id,
    _i8.Client? client,
    _i8.ClientTransport? transport,
  ) => super.noSuchMethod(
    Invocation.method(#registerClient, [id, client, transport]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.ClientInfo? getClientInfo(String? id) =>
      (super.noSuchMethod(Invocation.method(#getClientInfo, [id]))
          as _i9.ClientInfo?);

  @override
  _i8.Client? getClient(String? id) =>
      (super.noSuchMethod(Invocation.method(#getClient, [id])) as _i8.Client?);

  @override
  List<String> getAllClientIds() =>
      (super.noSuchMethod(
            Invocation.method(#getAllClientIds, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i4.Future<void> closeClient(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#closeClient, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> closeAll() =>
      (super.noSuchMethod(
            Invocation.method(#closeAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  Map<String, dynamic> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [MCPServerManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockMCPServerManager extends _i1.Mock implements _i10.MCPServerManager {
  MockMCPServerManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  String generateId() =>
      (super.noSuchMethod(
            Invocation.method(#generateId, []),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#generateId, []),
            ),
          )
          as String);

  @override
  void registerServer(
    String? id,
    _i11.Server? server,
    _i11.ServerTransport? transport,
  ) => super.noSuchMethod(
    Invocation.method(#registerServer, [id, server, transport]),
    returnValueForMissingStub: null,
  );

  @override
  void setLlmServer(String? id, _i12.LlmServer? llmServer) =>
      super.noSuchMethod(
        Invocation.method(#setLlmServer, [id, llmServer]),
        returnValueForMissingStub: null,
      );

  @override
  _i13.ServerInfo? getServerInfo(String? id) =>
      (super.noSuchMethod(Invocation.method(#getServerInfo, [id]))
          as _i13.ServerInfo?);

  @override
  _i11.Server? getServer(String? id) =>
      (super.noSuchMethod(Invocation.method(#getServer, [id])) as _i11.Server?);

  @override
  List<String> getAllServerIds() =>
      (super.noSuchMethod(
            Invocation.method(#getAllServerIds, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i4.Future<void> closeServer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#closeServer, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> closeAll() =>
      (super.noSuchMethod(
            Invocation.method(#closeAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  Map<String, dynamic> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [MCPLlmManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockMCPLlmManager extends _i1.Mock implements _i14.MCPLlmManager {
  MockMCPLlmManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  String generateId() =>
      (super.noSuchMethod(
            Invocation.method(#generateId, []),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#generateId, []),
            ),
          )
          as String);

  @override
  void registerLlm(String? id, _i12.McpLlm? mcpLlm, _i12.LlmClient? client) =>
      super.noSuchMethod(
        Invocation.method(#registerLlm, [id, mcpLlm, client]),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> addClientToLlm(String? llmId, _i8.Client? client) =>
      (super.noSuchMethod(
            Invocation.method(#addClientToLlm, [llmId, client]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i15.LlmInfo? getLlmInfo(String? id) =>
      (super.noSuchMethod(Invocation.method(#getLlmInfo, [id]))
          as _i15.LlmInfo?);

  @override
  _i12.LlmClient? getLlm(String? id) =>
      (super.noSuchMethod(Invocation.method(#getLlm, [id])) as _i12.LlmClient?);

  @override
  List<String> getAllLlmIds() =>
      (super.noSuchMethod(
            Invocation.method(#getAllLlmIds, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i4.Future<void> closeLlm(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#closeLlm, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> closeAll() =>
      (super.noSuchMethod(
            Invocation.method(#closeAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  Map<String, dynamic> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [ResourceManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockResourceManager extends _i1.Mock implements _i16.ResourceManager {
  MockResourceManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get allKeys =>
      (super.noSuchMethod(Invocation.getter(#allKeys), returnValue: <String>[])
          as List<String>);

  @override
  int get count =>
      (super.noSuchMethod(Invocation.getter(#count), returnValue: 0) as int);

  @override
  void register<T>(
    String? key,
    T? resource,
    _i4.Future<void> Function(T)? disposeFunction, {
    int? priority = 100,
    List<String>? dependencies,
    String? tag,
  }) => super.noSuchMethod(
    Invocation.method(
      #register,
      [key, resource, disposeFunction],
      {#priority: priority, #dependencies: dependencies, #tag: tag},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void registerSubscription(
    String? key,
    _i4.StreamSubscription<dynamic>? subscription, {
    int? priority = 100,
    List<String>? dependencies,
    String? tag,
  }) => super.noSuchMethod(
    Invocation.method(
      #registerSubscription,
      [key, subscription],
      {#priority: priority, #dependencies: dependencies, #tag: tag},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void registerCallback(
    String? key,
    _i4.Future<void> Function()? callback, {
    int? priority = 100,
    List<String>? dependencies,
    String? tag,
  }) => super.noSuchMethod(
    Invocation.method(
      #registerCallback,
      [key, callback],
      {#priority: priority, #dependencies: dependencies, #tag: tag},
    ),
    returnValueForMissingStub: null,
  );

  @override
  T? get<T>(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as T?);

  @override
  bool hasResource(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#hasResource, [key]),
            returnValue: false,
          )
          as bool);

  @override
  void addDependency(String? resource, String? dependsOn) => super.noSuchMethod(
    Invocation.method(#addDependency, [resource, dependsOn]),
    returnValueForMissingStub: null,
  );

  @override
  void removeDependency(String? resource, String? dependsOn) =>
      super.noSuchMethod(
        Invocation.method(#removeDependency, [resource, dependsOn]),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> dispose(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#dispose, [key]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> disposeAll() =>
      (super.noSuchMethod(
            Invocation.method(#disposeAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void registerWithTag<T>(
    String? key,
    T? resource,
    _i4.Future<void> Function(T)? disposeFunction,
    String? tag, {
    int? priority = 100,
    List<String>? dependencies,
  }) => super.noSuchMethod(
    Invocation.method(
      #registerWithTag,
      [key, resource, disposeFunction, tag],
      {#priority: priority, #dependencies: dependencies},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> disposeByTag(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#disposeByTag, [tag]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  List<String> getKeysByTag(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#getKeysByTag, [tag]),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  Map<String, dynamic> getStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getStatistics, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );
}
