name: mcp_integration_app
description: A demo application for Flutter MCP integration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # MCP packages
  mcp_client: ^0.1.6
  mcp_server: ^0.1.7
  mcp_llm: ^0.0.1
  flutter_mcp: ^0.1.0

  # UI and utilities
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  file_picker: ^5.3.0

  # For platform-specific features
  flutter_local_notifications: ^15.1.0+1
  tray_manager: ^0.2.0
  flutter_background_service: ^5.0.2
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/