name: flutter_mcp
description: Flutter plugin that integrates MCP server, client, and LLM into a unified agent system. Provides background execution, notification, system tray, lifecycle management, secure data storage, and scheduling for cross-platform agent apps.
version: 1.0.4
homepage: https://app-appplayer.github.io/makemind
repository: https://github.com/app-appplayer/flutter_mcp
issue_tracker: https://github.com/app-appplayer/flutter_mcp/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  universal_html: ^2.2.4
  plugin_platform_interface: ^2.0.2

  # MCP Core libraries
  mcp_client: ^1.0.1
  mcp_server: ^1.0.2
  mcp_llm: ^1.0.2

  # Utility libraries
  path: ^1.9.1
  meta: ^1.16.0
  uuid: ^4.5.1
  intl: ^0.20.2
  yaml: ^3.1.3
  synchronized: ^3.3.1
  crypto: ^3.0.6
  pointycastle: ^3.9.1
  path_provider: ^2.1.5
  logging: ^1.2.0
  pub_semver: ^2.1.4
  shelf: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.6
  build_runner: ^2.4.6
  analyzer: ^7.4.1

flutter:

  plugin:
    platforms:
      android:
        package: com.example.flutter_mcp
        pluginClass: FlutterMcpPlugin
      ios:
        pluginClass: FlutterMcpPlugin
      linux:
        pluginClass: FlutterMcpPlugin
      macos:
        pluginClass: FlutterMcpPlugin
      windows:
        pluginClass: FlutterMcpPluginCApi
      web:
        pluginClass: FlutterMcpWeb
        fileName: flutter_mcp_web.dart
